
INSERT INTO TONT_ZONAS VALUES ('Z01', 'Zona 1');
INSERT INTO TONT_ZONAS VALUES ('Z02', 'Zona 2');

INSERT INTO TONT_PAISES VALUES ('CO', 'Colombia', 'Z01');
INSERT INTO TONT_PAISES VALUES ('VE', 'Venezuela', 'Z01');
INSERT INTO TONT_PAISES VALUES ('ES', 'España', 'Z02');

INSERT INTO TONT_AVES VALUES ('AV_01', 'Ave 1', 'Avvv 1');
INSERT INTO TONT_AVES VALUES ('AV_02', 'Ave 2', 'Avvv 2');
INSERT INTO TONT_AVES VALUES ('AV_03', 'Ave 3', 'Avvv 3');
INSERT INTO TONT_AVES VALUES ('AV_04', 'Ave 4', 'Avvv 4');
INSERT INTO TONT_AVES VALUES ('AV_05', 'Ave 5', 'Avvv 5');


INSERT INTO TONT_AVES_PAIS VALUES ('AV_01', 'CO');
INSERT INTO TONT_AVES_PAIS VALUES ('AV_01', 'VE');
INSERT INTO TONT_AVES_PAIS VALUES ('AV_01', 'ES');
INSERT INTO TONT_AVES_PAIS VALUES ('AV_02', 'CO');
INSERT INTO TONT_AVES_PAIS VALUES ('AV_03', 'CO');
INSERT INTO TONT_AVES_PAIS VALUES ('AV_03', 'ES');
INSERT INTO TONT_AVES_PAIS VALUES ('AV_04', 'CO');
INSERT INTO TONT_AVES_PAIS VALUES ('AV_05', 'CO');